name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client openssh-server

      - name: Deploy to Testing Server;
        run: |
              ssh -v -o StrictHostKeyChecking=no -p "${{ secrets.PORT }}" "${{ secrets.USER }}@${{ secrets.IP }}" "git pull git@github.com:dheerajsr/appentus.git"

      - name: Run Deployment Commands
        run: |
          ssh -v -o StrictHostKey
