name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client openssh-server

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ip_address }}
          username: ${{ secrets.username }}
          password: ${{ secrets.ftp_password }}

      - name: Run Deployment Commands
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.username }}@${{ secrets.ip_address }} << EOF
          git clone git@github.com:dheerajsr/appentus.git
          # Add any other deployment commands here
          EOF
